# basics
service-name:
director-name:  ((service-name))-director
subdomain:
apps-prefix:
system-prefix:

# git
git-server:
git-user:
git-email:

# versions
stemcell-version:         "3445.11"
odb-sdk-version:          "0.16.1"

# pipeline configuration
iaas: vsphere

# vSphere configuration
vcenter-host:             ((vcenter-host))          # vCenter host or IP
vcenter-datacenter:       ((vcenter-datacenter))    # vCenter datacenter
vcenter-cluster:          ((vcenter-cluster))

# vCenter Cluster or Resource Pool to use to deploy Kubo.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
kubo-resource-pool: ((vcenter-resource-pool))

# Datastore to use for K8s machines and persistenet volumes
kubo-ephemeral-store:   ((slow-storage))
kubo-persistent-store:  ((slow-storage))

# folders/paths for vCenter
kubo-vm-folder: ((service-name))-vms
kubo-template-folder: ((service-name))-templates
kubo-disk-path: ((service-name))-disks

# state management in github
state-repository:         ((git-server)):((git-user))/((service-name))-state

# network configuration
director-ip:                    # IP address for the BOSH director
container-network:              # Infrastructure network name
network-cidr:                   # Infrastructure network CIDR, ex: 10.0.0.0/22
excluded-range:                 # Infrastructure network exclusion range
network-dns:                    # Infrastructure network DNS
network-gateway:                # Infrastructure network Gateway

# routing configuration
routing-mode: cf
k8s-master-host: tcp.((subdomain))                               # Hostname of TCP router. Use `cf domains` to find existing TCP domain. If none exists, see https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains for instructions to create one.
k8s-master-port: 1120
pcf-api-url:     https://api.((system-prefix)).((subdomain))     # TCP routing API URL. In PCF: https://api.<system domain>
pcf-uaa-url:     https://uaa.((system-prefix)).((subdomain))     # Routing UAA URL In PCF: https://uaa.<system domain>
pcf-apps-domain:   ((apps-prefix)).((subdomain))             # Cloud Foundry apps domain
pcf-system-domain:   ((system-prefix)).((subdomain))             # Cloud Foundry system domain

pcf-nats-internal-ips:
- ((pcf-nats-internal-ip-1))
pcf-nats-port: 4222
